
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    ignore:
      # Ignore some updates to the 'express' package
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    labels:
      - "npm-dependencies"
    # Allow up to 10 open pull requests
    open-pull-requests-limit: 10
  # Enable version updates for docker
  - package-ecosystem: "docker"
    directory: "/"
    # Check the docker registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    ignore:
      # Ignore some updates to the 'express' package
      - dependency-name: "node"
        update-types: [ "version-update:semver-major" ]
    labels:
      - "docker-dependencies"
