version: "3.9"

volumes:
  redis_cache:

networks:
  prerender:
    driver: bridge

services:
  redis:
    command: redis-server --save 20 1 --loglevel warning
    container_name: redis
    image: redis:6.2-alpine
    logging:
      driver: local
    networks:
      - prerender
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_cache:/var/cache/redis

  prerender:
    build:
      context: prerender
    container_name: prerender
    environment:
      PRERENDER_PORT: 3000
    init: true
    logging:
      driver: local
    networks:
      - prerender
    ports:
      - "3000:3000"
    restart: unless-stopped

  prerender-api:
    build:
      context: .
    container_name: prerender-api
    command: npm run start:dev
    depends_on:
      - redis
      - prerender
    environment:
      DEBUG: 1
      PORT: 3001
      PRERENDER_URL: http://prerender:3000
      REDIS_URL: redis://redis:6379/0
    init: true
    logging:
      driver: local
    networks:
      - prerender
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - .:/opt/app/
      - /opt/app/node_modules
