version: "3.8"

services:
  main:
    container_name: nest-prerender
    build:
      context: .
    tty: true
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

volumes:
  cache:
