version: "3.8"

services:
  main:
    container_name: nest-prerender
    build:
      context: .
    tty: true
    env_file:
      - .env
    depends_on:
      - cache
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

  cache:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data/cache

volumes:
  cache:
