# This is a basic workflow to help you get started with Actions

name: Pull request

# Controls when the action will run. Triggers the workflow on pull request to master
on:
  pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pull-request"
  pull-request:
    name: Pull request
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main
    strategy:
      matrix:
        node-version: [16]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: PR Auto assign
        uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto-assign.yml" # Only needed if you use something other than .github/auto_assign.yml
      - name: Labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: NPM - Use NPM latest version
        run: npm install --location=global npm@latest
      - name: NPM - Install dependencies
        run: npm ci
      - name: EDITORCONFIG - Check if your files consider your .editorconfig rules.
        run: npm run editorconfig # check code by .editorconfig
      - name: ESLint - An AST-based pattern checker for JavaScript
        run: npm run lint
      - name: Jest - Launches the test runner in the interactive watch mode.
        run: npm run test
      - name: Build - Builds the app for production to the build folder.
        run: CI=false npm run build
